### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Akalinsky/superhumans_and_cats_and_users#1]
This is looking mostly good, except I *would* like to see a link to the Show page when not logged in.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by Akalinsky** [comment]
I made the changes. I see them live on my end, do you see them live on your end? I resubmitted the codekwondo showcase just incase that didn't properly update on Sunday when I submitted it.

**Comment by chrisvfritz** [comment]
:+1: Looking good. You just need to comment here when you've finished updating in the futer, then I'll know to take another look. :smiley:
